<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<UseWPF>true</UseWPF>
		<AssemblyName>MixItUp-Setup</AssemblyName>
		<RootNamespace>MixItUp.Installer</RootNamespace>
		<ApplicationIcon>Logo.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<AssemblyTitle>MixItUp.Installer</AssemblyTitle>
		<Product>MixItUp.Installer</Product>
		<Description>Mix It Up Desktop Installer</Description>
		<Company>Blazing Cacti LLC</Company>
		<Copyright>Copyright © 2026 Blazing Cacti LLC, All Rights Reserved.</Copyright>
		<AssemblyVersion>0.6.0.0</AssemblyVersion>
		<FileVersion>0.6.0.0</FileVersion>
		<Version>0.6.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="MdXaml" Version="1.27.0" />
		<PackageReference Include="MdXaml.Plugins" Version="1.27.0" />
		<PackageReference Include="AvalonEdit" Version="6.3.1.120" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.IO.Compression.FileSystem" />
		<Reference Include="System.Runtime.Serialization" />
		<Reference Include="System.Net.Http" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\MixItUp.Base\Model\API\MixItUpUpdateModel.cs" Link="MixItUpUpdateModel.cs" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Logo.ico" />
		<Resource Include="Logo.png" />
	</ItemGroup>

	<Target Name="EmbedReferencedAssemblies" AfterTargets="ResolveReferences">
		<ItemGroup>
			<EmbeddedResource Include="@(ReferenceCopyLocalPaths)" Condition="'%(ReferenceCopyLocalPaths.Extension)' == '.dll'">
				<LogicalName>%(ReferenceCopyLocalPaths.FileName)%(ReferenceCopyLocalPaths.Extension)</LogicalName>
			</EmbeddedResource>
		</ItemGroup>
	</Target>

	<Target Name="CleanupOutputDlls" AfterTargets="AfterBuild" Condition="'$(Configuration)' == 'Release'">
		<ItemGroup>
			<DllFiles Include="$(OutputPath)*.dll" />
		</ItemGroup>
		<Delete Files="@(DllFiles)" />
		<Message Text="Removed DLL files from output" Importance="High" />
	</Target>
</Project>