<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyTitle>MixItUp.API</AssemblyTitle>
    <AssemblyVersion>1.6.30.0</AssemblyVersion>
    <FileVersion>1.6.30.0</FileVersion>
		<Company>Blazing Cacti LLC</Company>
		<Copyright>Copyright © 2026 Blazing Cacti LLC, All Rights Reserved. </Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>1701;1702;CS8603;CS8618;CS8625</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>1701;1702;CS8603;CS8618;CS8625</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
